<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.sql.*,java.util.*" %>
<%
String dbUrl = System.getenv("ORACLE_URL");
String dbUser = System.getenv("ORACLE_USER");
String dbPass = System.getenv("ORACLE_PASS");
if(dbUrl==null) dbUrl="jdbc:oracle:thin:@//localhost:1521/orcl";
if(dbUser==null) dbUser="info";
if(dbPass==null) dbPass="pro";
Class.forName("oracle.jdbc.OracleDriver");
String q = Optional.ofNullable(request.getParameter("q")).orElse("").trim();
String cat = Optional.ofNullable(request.getParameter("cat")).orElse("ALL").trim();
boolean doReset = "1".equals(request.getParameter("reset"));
List<Map<String,Object>> threads = new ArrayList<>();
int totalThreads = 0;
try{
  Class.forName("oracle.jdbc.OracleDriver");
  try(Connection con = DriverManager.getConnection(dbUrl, dbUser, dbPass)){
  boolean hasCategories=false, hasThreads=false, hasReplies=false;
  try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
    ps.setString(1, "CATEGORIES"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasCategories = rs.getInt(1)>0; }
  }
  try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
    ps.setString(1, "THREADS"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasThreads = rs.getInt(1)>0; }
  }
  try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
    ps.setString(1, "REPLIES"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasReplies = rs.getInt(1)>0; }
  }
  if(!hasCategories){
    try(Statement st = con.createStatement()){
      st.executeUpdate("CREATE TABLE categories (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(50) NOT NULL)");
    }
  }
  if(!hasThreads){
    try(Statement st = con.createStatement()){
      st.executeUpdate("CREATE TABLE threads (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_id NUMBER, title VARCHAR2(200) NOT NULL, author_name VARCHAR2(100), content CLOB, created_at DATE DEFAULT SYSDATE, updated_at DATE)");
      st.executeUpdate("ALTER TABLE threads ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL");
    }
  }
  if(!hasReplies){
    try(Statement st = con.createStatement()){
      st.executeUpdate("CREATE TABLE replies (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, thread_id NUMBER NOT NULL, author_name VARCHAR2(100), content CLOB, created_at DATE DEFAULT SYSDATE)");
      st.executeUpdate("ALTER TABLE replies ADD CONSTRAINT fk_thread FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE");
    }
  }
  int catCount = 0;
  try(Statement st = con.createStatement(); ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM categories")){
    if(rs.next()) catCount = rs.getInt(1);
  }
  if(catCount==0){
    try(PreparedStatement ps = con.prepareStatement("INSERT INTO categories(name) VALUES(?)")){
      String[] catsSeed = {"お知らせ","宿題・提出物","授業のポイント","質問コーナー","自由メッセージ","忘れ物・落とし物","先生からのメッセージ"};
      for(String cseed: catsSeed){ ps.setString(1, cseed); ps.executeUpdate(); }
    }
  }
  if(doReset){
    try(Statement st = con.createStatement()){
      st.executeUpdate("DELETE FROM replies");
      st.executeUpdate("DELETE FROM threads");
    }
    response.sendRedirect("index.jsp?resetDone=1");
    return;
  }
  try(Statement st = con.createStatement()){
    try(ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM threads")){
      if(rs.next()) totalThreads = rs.getInt(1);
    }
  }
  String sql = "SELECT t.id,t.title,t.author_name,t.created_at,t.updated_at,c.name AS category,(SELECT COUNT(*) FROM replies r WHERE r.thread_id=t.id) AS reply_count FROM threads t LEFT JOIN categories c ON c.id=t.category_id";
  List<Object> params = new ArrayList<>();
  List<String> conds = new ArrayList<>();
  if(q.length()>0){
    conds.add("(LOWER(t.title) LIKE ? OR LOWER(t.author_name) LIKE ? OR LOWER(c.name) LIKE ?)");
    String qp = "%" + q.toLowerCase() + "%";
    params.add(qp); params.add(qp); params.add(qp);
  }
  if(cat.length()>0 && !"ALL".equalsIgnoreCase(cat)){
    conds.add("c.name = ?");
    params.add(cat);
  }
  if(!conds.isEmpty()){
    sql += " WHERE " + String.join(" AND ", conds);
  }
  sql += " ORDER BY NVL(t.updated_at,t.created_at) DESC";
  try(PreparedStatement ps = con.prepareStatement(sql)){
    for(int i=0;i<params.size();i++) ps.setObject(i+1, params.get(i));
    try(ResultSet rs = ps.executeQuery()){
      while(rs.next()){
        Map<String,Object> row = new HashMap<>();
        row.put("id", rs.getLong("id"));
        row.put("title", rs.getString("title"));
        row.put("author", rs.getString("author_name"));
        row.put("created_at", rs.getTimestamp("created_at"));
        row.put("updated_at", rs.getTimestamp("updated_at"));
        row.put("category", rs.getString("category"));
        row.put("reply_count", rs.getInt("reply_count"));
        threads.add(row);
      }
    }
  }
  }
} catch(Exception ex){
  threads.clear();
  totalThreads = 0;
}
%>
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Classroom 掲示板 - スレッド一覧</title>
  <link rel="stylesheet" href="<%=request.getContextPath()%>/Classroom_Keijiban1111/styles.css" />
  <style>
    .container{max-width:100%; margin:0; padding:0 16px;}
    .card{width:100%;}
    table{width:100%;}
    th, td{vertical-align:middle;}
    td:nth-child(1), td:nth-child(4){text-align:center;}
    td:nth-child(3){text-align:left;}
    .header .brand{display:flex; justify-content:space-between; align-items:flex-end;}
    .top-actions{display:flex; gap:8px; margin-left:auto;}
    .table-head{background:#eaf2ff; border:1px solid #d6e4ff; border-top-left-radius:12px; border-top-right-radius:12px; padding:10px 16px; color:#334155; font-weight:600;}
    table thead th{background:#eef2ff; border-bottom:1px solid #e5e7eb;}
    thead th:nth-child(1), thead th:nth-child(4), thead th:nth-child(5){text-align:center;}
    thead th:nth-child(2){text-align:center;}
    thead th:nth-child(3){text-align:left;}
    #threadBody tr td{padding-top:12px; padding-bottom:12px;}
    #threadBody .sub{margin-top:4px; font-size:12px; color:#64748b;}
    #threadBody .badge{background:#f1f5f9; border:1px solid #e2e8f0; padding:2px 6px; border-radius:999px;}
    td:nth-child(2){text-align:center;}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="brand">
        <div>
          <h1>Classroom 掲示板</h1>
          <small>Class-D (HTML/CSS/java/SQL) • Threads: <%= totalThreads %></small>
        </div>
        <div class="top-actions">
          <a class="btn primary" href="new.jsp">+ 新規スレッド</a>
          <a class="btn danger" href="logout">ログアウト</a>
          <form method="get" style="display:inline" onsubmit="return resetConfirm()">
            <input type="hidden" name="reset" value="1" />
            <button class="btn secondary danger" type="submit">Reset Data</button>
          </form>
        </div>
      </div>
      <div class="navbar">
        <div class="right">
          <form method="get" class="search">
            <input type="text" name="q" value="<%= q %>" placeholder="検索..." />
            <select name="cat">
              <option value="ALL"<%= "ALL".equalsIgnoreCase(cat)?" selected":"" %>>すべて</option>
              <%
              Set<String> catsSet = new LinkedHashSet<>();
              for(Map<String,Object> t: threads){
                String cn = (String)t.get("category");
                if(cn!=null && cn.trim().length()>0) catsSet.add(cn.trim());
              }
              java.util.List<String> cats = new java.util.ArrayList<>(catsSet);
              java.util.Collections.sort(cats, java.text.Collator.getInstance(java.util.Locale.JAPANESE));
              for(String c: cats){
              %>
              <option value="<%= c %>"<%= c.equals(cat)?" selected":"" %>><%= c %></option>
              <% } %>
            </select>
            <button class="btn secondary" type="submit">Filter</button>
          </form>
        </div>
      </div>
    </div>
    <div class="main">
      <div class="card">
        <div class="pad">
          <h2>Classroom 掲示板</h2>
          <div class="table-head">スレッド一覧</div>
          <table style="table-layout:fixed">
        <colgroup>
          <col style="width:70px" />
          <col />
          <col style="width:140px" />
          <col style="width:80px" />
          <col style="width:170px" />
        </colgroup>
        <thead>
          <tr>
            <th style="width:70px">番号</th>
            <th>カテゴリ</th>
            <th style="width:140px">名前</th>
            <th style="width:80px">返信</th>
            <th style="width:170px">最終更新</th>
          </tr>
        </thead>
        <tbody id="threadBody">
          <%
          for(Map<String,Object> t: threads){
            long id = (Long)t.get("id");
            String title = (String)t.get("title");
            String author = (String)t.get("author");
            int replies = (Integer)t.get("reply_count");
            java.sql.Timestamp upd = (java.sql.Timestamp)t.get("updated_at");
            java.sql.Timestamp crt = (java.sql.Timestamp)t.get("created_at");
            java.sql.Timestamp show = upd!=null?upd:crt;
            String catName = (String)t.get("category");
          %>
          <tr onclick="location.href='thread.jsp?id=<%= id %>'">
            <td style="width:70px"><%= id %></td>
            <td style="text-align:center"><%= catName==null?"—":catName %></td>
            <td style="width:140px"><%= author %></td>
            <td style="width:80px"><%= replies %></td>
            <td style="width:170px"><%= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm").format(show) %></td>
          </tr>
          <%
          }
          %>
          <tr id="emptyTipRow"><td colspan="5" style="text-align:center; color:#64748b">Tip: スレッドをクリックして開きます。</td></tr>
        </tbody>
      </table>
        </div>
      </div>
    </div>
  </div>
  <script>
    (function(){
      function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
      function fmt(iso){
        try{
          var d=new Date(iso);
          var p=function(n){return String(n).padStart(2,"0");};
          return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+" "+p(d.getHours())+":"+p(d.getMinutes());
        }catch(e){return iso;}
      }
      var raw=localStorage.getItem("classd_fallback_threads");
      if(!raw) return;
      var list=[];
      try{ list=JSON.parse(raw)||[]; }catch(e){ list=[]; }
      if(!Array.isArray(list) || list.length===0) return;
      var sp = new URLSearchParams(location.search);
      var qv = (sp.get("q")||"").toLowerCase();
      var cv = sp.get("cat")||"ALL";
      list = list.filter(function(t){
        var ok = true;
        if(qv){
          var s = qv;
          var f = ((t.title||"").toLowerCase().indexOf(s)>=0) || ((t.author||"").toLowerCase().indexOf(s)>=0) || ((t.category||"").toLowerCase().indexOf(s)>=0);
          ok = ok && f;
        }
        if(cv && cv!=="ALL"){
          ok = ok && ((t.category||"")===cv);
        }
        return ok;
      });
      list.sort(function(a,b){ return String(b.updated_at||"").localeCompare(String(a.updated_at||"")); });
      var tbody=document.getElementById("threadBody");
      var totalEl=document.querySelector(".brand small");
      var rows=list.map(function(t){
        var rid=esc(String(t.id));
        var replies=Number(t.reply_count||0);
        return "<tr onclick=\"location.href='thread.jsp?id="+rid+"'\">"
          +"<td style=\"width:70px\">"+rid+"</td>"
          +"<td style=\\\"text-align:center\\\">"+esc(t.category||"—")+"</td>"
          +"<td style=\"width:140px\">"+esc(t.author||"")+"</td>"
          +"<td style=\"width:80px\">"+replies+"</td>"
          +"<td style=\"width:170px\">"+fmt(t.updated_at||t.created_at)+"</td>"
          +"</tr>";
      }).join("");
      if(tbody && rows){ tbody.insertAdjacentHTML("beforeend", rows); }
      try{
        if(rows){
          var tip=document.getElementById("emptyTipRow");
          if(tip) tip.remove();
        }
      }catch(e){}
      if(list.length>0){
        var tip=document.getElementById("emptyTipRow");
        if(tip) tip.remove();
      }
      try{
        var txt=totalEl && totalEl.textContent ? totalEl.textContent : "";
        var m=txt.match(/Threads:\s*(\d+)/);
        if(m){ var n=Number(m[1]||0)+list.length; totalEl.textContent=txt.replace(/Threads:\s*\d+/, "Threads: "+n); }
      }catch(e){}
    })();
  </script>
  <script>
    (function(){
      function clearFallback(){
        try{
          localStorage.removeItem("classd_fallback_threads");
          localStorage.removeItem("classd_fallback_replies");
          localStorage.removeItem("classd_last_thread_id");
        }catch(e){}
      }
      window.resetConfirm = function(){
        try{
          var ok = confirm("Reset गर्दा सबै दर्ज गरिएको डाटा मेटिन्छ। जारी राख्ने?");
          if(!ok) return false;
          clearFallback();
          return true;
        }catch(e){
          return true;
        }
      };
      try{
        var p = new URLSearchParams(location.search);
        if(p.get("resetDone")==="1"){
          clearFallback();
          p.delete("resetDone");
          var url = location.pathname + (p.toString()?("?"+p.toString()):"");
          history.replaceState(null, "", url);
        }
      }catch(e){}
    })();
  </script>
</body>
</html>
