package filter;

import jakarta.servlet.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import util.DBUtil;

import java.io.IOException;
import java.sql.*;
import java.util.*;

public class IndexDataFilter implements Filter {
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest req = (HttpServletRequest) request;
        HttpServletResponse resp = (HttpServletResponse) response;
        String q = Optional.ofNullable(req.getParameter("q")).orElse("").trim();
        String cat = Optional.ofNullable(req.getParameter("cat")).orElse("ALL").trim();
        boolean doReset = "1".equals(req.getParameter("reset"));
        List<Map<String,Object>> threads = new ArrayList<>();
        int totalThreads = 0;
        try (Connection con = DBUtil.getConnection()) {
            boolean hasCategories=false, hasThreads=false, hasReplies=false;
            try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
                ps.setString(1, "CATEGORIES"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasCategories = rs.getInt(1)>0; }
            }
            try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
                ps.setString(1, "THREADS"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasThreads = rs.getInt(1)>0; }
            }
            try(PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM user_tables WHERE table_name=?")){
                ps.setString(1, "REPLIES"); try(ResultSet rs = ps.executeQuery()){ if(rs.next()) hasReplies = rs.getInt(1)>0; }
            }
            if(!hasCategories){
                try(Statement st = con.createStatement()){
                    st.executeUpdate("CREATE TABLE categories (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(50) NOT NULL)");
                }
            }
            if(!hasThreads){
                try(Statement st = con.createStatement()){
                    st.executeUpdate("CREATE TABLE threads (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_id NUMBER, title VARCHAR2(200) NOT NULL, author_name VARCHAR2(100), content CLOB, created_at DATE DEFAULT SYSDATE, updated_at DATE)");
                    st.executeUpdate("ALTER TABLE threads ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL");
                }
            }
            if(!hasReplies){
                try(Statement st = con.createStatement()){
                    st.executeUpdate("CREATE TABLE replies (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, thread_id NUMBER NOT NULL, author_name VARCHAR2(100), content CLOB, created_at DATE DEFAULT SYSDATE)");
                    st.executeUpdate("ALTER TABLE replies ADD CONSTRAINT fk_thread FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE");
                }
            }
            int catCount = 0;
            try(Statement st = con.createStatement(); ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM categories")){
                if(rs.next()) catCount = rs.getInt(1);
            }
            if(catCount==0){
                try(PreparedStatement ps = con.prepareStatement("INSERT INTO categories(name) VALUES(?)")){
                    String[] catsSeed = {"お知らせ","宿題・提出物","授業のポイント","質問コーナー","自由メッセージ","忘れ物・落とし物","先生からのメッセージ"};
                    for(String cseed: catsSeed){ ps.setString(1, cseed); ps.executeUpdate(); }
                }
            }
            if(doReset){
                try(Statement st = con.createStatement()){
                    st.executeUpdate("DELETE FROM replies");
                    st.executeUpdate("DELETE FROM threads");
                }
                resp.sendRedirect("index.jsp?resetDone=1");
                return;
            }
            try(Statement st = con.createStatement()){
                try(ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM threads")){
                    if(rs.next()) totalThreads = rs.getInt(1);
                }
            }
            String sql = "SELECT t.id,t.title,t.author_name,t.content,t.created_at,t.updated_at,c.name AS category,(SELECT COUNT(*) FROM replies r WHERE r.thread_id=t.id) AS reply_count FROM threads t LEFT JOIN categories c ON c.id=t.category_id";
            List<Object> params = new ArrayList<>();
            List<String> conds = new ArrayList<>();
            if(q.length()>0){
                conds.add("(LOWER(t.title) LIKE ? OR LOWER(t.author_name) LIKE ? OR LOWER(c.name) LIKE ?)");
                String qp = "%" + q.toLowerCase() + "%";
                params.add(qp); params.add(qp); params.add(qp);
            }
            if(cat.length()>0 && !"ALL".equalsIgnoreCase(cat)){
                conds.add("c.name = ?");
                params.add(cat);
            }
            if(!conds.isEmpty()){
                sql += " WHERE " + String.join(" AND ", conds);
            }
            sql += " ORDER BY NVL(t.updated_at,t.created_at) DESC";
            try(PreparedStatement ps = con.prepareStatement(sql)){
                for(int i=0;i<params.size();i++) ps.setObject(i+1, params.get(i));
                try(ResultSet rs = ps.executeQuery()){
                    while(rs.next()){
                        Map<String,Object> row = new HashMap<>();
                        row.put("id", rs.getLong("id"));
                        row.put("title", rs.getString("title"));
                        row.put("author", rs.getString("author_name"));
                        row.put("content", rs.getString("content"));
                        row.put("created_at", rs.getTimestamp("created_at"));
                        row.put("updated_at", rs.getTimestamp("updated_at"));
                        row.put("category", rs.getString("category"));
                        row.put("reply_count", rs.getInt("reply_count"));
                        threads.add(row);
                    }
                }
            }
        } catch (Exception ex) {
            threads.clear();
            totalThreads = 0;
        }
        request.setAttribute("threads", threads);
        request.setAttribute("totalThreads", totalThreads);
        chain.doFilter(request, response);
    }
}
