CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) NOT NULL
);
ALTER TABLE users ADD (
  email VARCHAR2(255),
  reset_token VARCHAR2(255),
  token_expiry TIMESTAMP
);

CREATE TABLE threads (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id NUMBER,
  title VARCHAR2(200) NOT NULL,
  author_name VARCHAR2(100),
  content CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP
);

ALTER TABLE threads
  ADD CONSTRAINT fk_category
  FOREIGN KEY (category_id)
  REFERENCES categories(id)
  ON DELETE SET NULL;

CREATE TABLE replies (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id NUMBER NOT NULL,
  author_name VARCHAR2(100),
  content CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE replies
  ADD CONSTRAINT fk_thread
  FOREIGN KEY (thread_id)
  REFERENCES threads(id)
  ON DELETE CASCADE;

CREATE INDEX idx_threads_category ON threads(category_id);
CREATE INDEX idx_replies_thread ON replies(thread_id);

INSERT INTO categories(name) VALUES('お知らせ');
INSERT INTO categories(name) VALUES('宿題・提出物');
INSERT INTO categories(name) VALUES('授業のポイント');
INSERT INTO categories(name) VALUES('質問コーナー');
INSERT INTO categories(name) VALUES('自由メッセージ');
INSERT INTO categories(name) VALUES('忘れ物・落とし物');
INSERT INTO categories(name) VALUES('先生からのメッセージ');
