DROP TABLE replies CASCADE CONSTRAINTS;
DROP TABLE threads CASCADE CONSTRAINTS;
DROP TABLE categories CASCADE CONSTRAINTS;

CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) NOT NULL
);


CREATE TABLE threads (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id NUMBER,
  title VARCHAR2(200) NOT NULL,
  author_name VARCHAR2(100),
  content CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP
);


ALTER TABLE threads
  ADD CONSTRAINT fk_category
  FOREIGN KEY (category_id)
  REFERENCES categories(id)
  ON DELETE SET NULL;


CREATE TABLE replies (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id NUMBER NOT NULL,
  author_name VARCHAR2(100),
  content CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);


ALTER TABLE replies
  ADD CONSTRAINT fk_thread
  FOREIGN KEY (thread_id)
  REFERENCES threads(id)
  ON DELETE CASCADE;


CREATE INDEX idx_threads_category ON threads(category_id);
CREATE INDEX idx_replies_thread ON replies(thread_id);


INSERT INTO categories(name) VALUES('お知らせ');
INSERT INTO categories(name) VALUES('宿題・提出物');
INSERT INTO categories(name) VALUES('授業のポイント');
INSERT INTO categories(name) VALUES('質問コーナー');
INSERT INTO categories(name) VALUES('自由メッセージ');
INSERT INTO categories(name) VALUES('忘れ物・落とし物');
INSERT INTO categories(name) VALUES('先生からのメッセージ');

CREATE TABLE USERS (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE
);

ALTER TABLE threads ADD file_name VARCHAR2(255);

COMMIT;


SELECT USER FROM dual;

SELECT author_name, content, created_at, file_name
FROM replies
WHERE thread_id = 21
ORDER BY created_at DESC;

DESC replies;

ALTER TABLE replies ADD (FILE_NAME VARCHAR2(255));
COMMIT;

SELECT thread_id, author_name, content, created_at, file_name
FROM replies
ORDER BY created_at DESC;

INSERT INTO categories (id, name) VALUES (1, 'Announcement');

-- 0) Clean existing demo data (FK-safe order)
DELETE FROM replies;
DELETE FROM threads;
DELETE FROM categories;
DELETE FROM users;
COMMIT;

-- 1) Users (login accounts)
INSERT INTO users (username, password) VALUES ('yya',   'pass123');
INSERT INTO users (username, password) VALUES ('ridoy', 'test123');
INSERT INTO users (username, password) VALUES ('kabi',  'demo123');
COMMIT;

-- 2) Categories (use your original Japanese categories)
INSERT INTO categories(name) VALUES('お知らせ');
INSERT INTO categories(name) VALUES('宿題・提出物');
INSERT INTO categories(name) VALUES('授業のポイント');
INSERT INTO categories(name) VALUES('質問コーナー');
INSERT INTO categories(name) VALUES('自由メッセージ');
INSERT INTO categories(name) VALUES('忘れ物・落とし物');
INSERT INTO categories(name) VALUES('先生からのメッセージ');
COMMIT;

-- Helper: use category id by name
-- (SELECT id FROM categories WHERE name='質問コーナー')

-- 3) Threads (7 threads, set updated_at too)
INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='お知らせ'),
  '【デモ】掲示板へようこそ（機能一覧）',
  'yya',
  'この掲示板は「スレッド投稿」「返信」「編集・削除（投稿者のみ）」「カテゴリ」「添付ファイル」に対応しています。発表用のデモデータです。',
  SYSTIMESTAMP, SYSTIMESTAMP, NULL
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='質問コーナー'),
  'JSPで一覧が表示されない（forward確認）',
  'ridoy',
  'スレッド一覧が表示されません。BoardServletでSQL→setAttribute→forwardの流れを確認中です。',
  SYSTIMESTAMP, SYSTIMESTAMP, NULL
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='宿題・提出物'),
  '第3回レポート提出（PDF添付）',
  'kabi',
  '課題レポートを提出します。添付ファイル機能のデモも兼ねています。',
  SYSTIMESTAMP, SYSTIMESTAMP, 'report3.pdf'
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='授業のポイント'),
  '正規化のポイントまとめ（1NF?3NF）',
  'yya',
  '1NF: 繰り返し属性をなくす / 2NF: 部分関数従属をなくす / 3NF: 推移関数従属をなくす、という流れで理解しました。',
  SYSTIMESTAMP, SYSTIMESTAMP, NULL
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='質問コーナー'),
  'ORA-00904（無効な識別子）エラー',
  'ridoy',
  '列名のスペルやテーブル別名（エイリアス）を間違えると発生します。DESCで列名を確認します。',
  SYSTIMESTAMP, SYSTIMESTAMP, NULL
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='自由メッセージ'),
  '発表前チェックリスト（デモ手順）',
  'kabi',
  '①ログイン → ②スレッド作成 → ③返信 → ④編集/削除 → ⑤添付ファイル確認 の順で発表します。',
  SYSTIMESTAMP, SYSTIMESTAMP, NULL
);

INSERT INTO threads (category_id, title, author_name, content, created_at, updated_at, file_name)
VALUES (
  (SELECT id FROM categories WHERE name='忘れ物・落とし物'),
  'USBメモリ見つけました',
  'yya',
  '教室にUSBメモリが落ちていました。心当たりがある人は連絡してください。',
  SYSTIMESTAMP, SYSTIMESTAMP, 'usb_photo.png'
);

COMMIT;

-- 4) Replies (insert safely by selecting thread_id using title)
-- Thread: 【デモ】掲示板へようこそ（機能一覧）
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='【デモ】掲示板へようこそ（機能一覧）'),
  'ridoy',
  'いいですね！ログインユーザーと投稿者が一致すると編集・削除が表示される点も説明できそうです。',
  SYSTIMESTAMP, NULL
);

INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='【デモ】掲示板へようこそ（機能一覧）'),
  'kabi',
  '添付ファイル付き投稿もあるので、デモで見せると印象が良くなります。',
  SYSTIMESTAMP, NULL
);

-- Thread: JSPで一覧が表示されない（forward確認）
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='JSPで一覧が表示されない（forward確認）'),
  'yya',
  'request.setAttributeのキー名がJSP側と一致しているか確認してみてください。',
  SYSTIMESTAMP, NULL
);

INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='JSPで一覧が表示されない（forward確認）'),
  'kabi',
  'DBが0件だと画面が空になるので、テストデータを入れて確認すると早いです。',
  SYSTIMESTAMP, NULL
);

-- Thread: 第3回レポート提出（PDF添付）
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='第3回レポート提出（PDF添付）'),
  'yya',
  '提出ありがとうございます。内容を確認します。',
  SYSTIMESTAMP, NULL
);

INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='第3回レポート提出（PDF添付）'),
  'kabi',
  '補足資料も添付します。',
  SYSTIMESTAMP, 'appendix.png'
);

-- Thread: 正規化のポイントまとめ（1NF?3NF）
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='正規化のポイントまとめ（1NF?3NF）'),
  'ridoy',
  '2NFの「部分関数従属」が一番つまずきました。複合主キーのときに起きやすいですね。',
  SYSTIMESTAMP, NULL
);

-- Thread: ORA-00904（無効な識別子）エラー
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='ORA-00904（無効な識別子）エラー'),
  'yya',
  'エイリアスを使っている場合は、"T"."COLUMN" の指定が正しいかも確認すると良いです。',
  SYSTIMESTAMP, NULL
);

-- Thread: 発表前チェックリスト（デモ手順）
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='発表前チェックリスト（デモ手順）'),
  'ridoy',
  'OKです！私は返信とファイルアップロードのところを説明します。',
  SYSTIMESTAMP, NULL
);

-- Thread: USBメモリ見つけました
INSERT INTO replies (thread_id, author_name, content, created_at, file_name)
VALUES (
  (SELECT id FROM threads WHERE title='USBメモリ見つけました'),
  'kabi',
  '写真ありがとうございます。心当たりの人に共有します。',
  SYSTIMESTAMP, NULL
);

COMMIT;

-- 5) Quick check
SELECT COUNT(*) AS thread_count FROM threads;
SELECT COUNT(*) AS reply_count  FROM replies;